# Generated by Django 6.1.1 on 2026-09-07 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('recurrence', models.CharField(choices=[('none', 'One-off'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Recurring templates can be deactivated without deleting history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChoreInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('done', 'Done')], default='open', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='chores.chore')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_instances', to='chores.person')),
            ],
            options={
                'verbose_name_plural': 'chore instances',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_awarded', models.PositiveIntegerField(help_text="Snapshot of the chore's point value at completion time.")),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='chores.choreinstance')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='chores.person')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
